# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c2b8fa38d17b972c4b81642c1b5da11676ba05b050173364a9c08912de39e2f663b31288648a62777519b6cda31e25747319b50bf5c89e1f04fe4899590a1e7

test:
  secret_key_base: 79877ed82eac815d8e4ed9f95ee3335d8bb74ba1ae90dd806c46308fc61d92e0ecec7150e67654a6a7fe4b6615346a2ba4e4c72dc26ae4c1b5ef02fdcbcc09cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
