# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c42842c30b575ea1857c3acf69ab88641070a4a0da80eb8f00182055192d8893849e054a4fa304a70faf3d16e0144e932a6f15e7d28be0a767aa113d8eeccf2

test:
  secret_key_base: 5671cf22d117c93922b26b3becb00c8d8ff75bf2792beb4d4040f3e6b1b546d1ba625a5979c379992083c586c1c63f22a506488a84adc5e98b10ca93b099612a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
