# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dc3dc44631fd91ae840299627253898ebbe8fa840d9f39443349d60f7d619de73d896089a9a46b2af063195be96c4e60b06a825421eb019f63f99331d12669b

test:
  secret_key_base: 0bb0795ae38976ad0d523ea43589290890f0ba761432879aa132e7419db766b0f81c4248a7b3a92ea8af5ad8d80420b2e717c93bdf2e936241623b63f005dd0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
