# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78bc60e303bfbbe76ee8cb964e5fa261177f0d6b777dc23fa52f5fae91cb85c8dbcb067bfc4359b539e77cdc30984a4130ce8296f2dc58b13764e39e598ce5cd

test:
  secret_key_base: 8eb7a30b9cf4a8f6f3480416c18346130e829584e97ee9ec0e030bc3b8a5798a1c2e3b29325008cdeef4d397db67d4933e3087931d8f56658021ccfb5920bbde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
