# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 523a701f38c8fad590222713451a8720e4a4d72da09e49028111e19bc5315c5f0860966ed49e80c2c052654e2c890fb83a968dd81ce264b312b7a736182bc904

test:
  secret_key_base: af38f7d19caa2e19a14e894ab249dbbe04f360f8863b7e2771cd6c732e0e8abd125d527e68a1390360a1b044eac5e97410fd3c763734e6949ce92359535f32da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
