source 'https://rubygems.org'

gem 'rails', '4.1.0'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'ffaker'


# Don't log CSS/JS file requests to log file
gem 'quiet_assets'

group :development do
  gem 'pry-rails'
  gem 'better_errors'
  gem 'rack-mini-profiler'
end
