# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22db4f81ebb2fd94bf02657714fca4dd1858375bdbc62eda2c8f15d32f674a9df49644c70eb84dbd6e69f63eb83443bf3c8de2e4dc490a1a51387a03c3a34c8e

test:
  secret_key_base: c93b2625222eaff173efc7ef65034847f31d429b02c85f200d67c254f35c41a6b7796cdb04a06ff70e78917d70f9e23f2a8f657578887070e448080efde6af75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
