# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d8bffb2fa444ce59e0be247b7b521603a8e0b75bdf298c7e5e8a8f857dc987d4b475630b6c57a679bfce986962b6ca3837c2ce939041c995152758822e8e914

test:
  secret_key_base: 94eab9c78363a3ca60ba917da65f27772713deb1c33bc923f214c8e4e0d407ebedaae4041373d0a866935321dbc87fddb56288559784bee5ab70bb3b3d94aa5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
