# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3df0bfc275d4f9a921e95fe79e7431d8702d8ea513366d7d2ee02670e9254e647f846cddf5969e0b667f7d78859c504c9711e56934806a74ad95298604375bc1

test:
  secret_key_base: 12b08b647f31ae2fd833003034948f68a4f5811307b7e054e6140141150d6dd3e8b5457ad84e7f02b9dcc74333e494c70bb01dea03224aacc7826937c8800311

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
