# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f8452fe03792f50e28f60cacc7f46365b8ca0064ba70eb499ae67f24f150ce3a1eda3c4f2dd0a34681a443ed59d7ca52a4b4577cedf0f105da5021a9fc3c062

test:
  secret_key_base: c13d94ab650b9db34091d2794b981a27ef8540a83f08bfb7705fd96189c60bd920e22d1be17680db6fc0311f7ea41fa38a3fc32a42de6eeb7626d592e5bf6ead

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
