# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e11374b8df87f29445ce89c7dcdacfd1aa276b975d6027dd95c0df5b9c9e088870ce322d1dfed92e2eaa8165ba7fe55ed86a46f47603123a2cab961e4608b37b

test:
  secret_key_base: 0160969eb20a07149f17d2b65f94798cb3a0c224b403708003d139f401d2407b836221a3293a05b3e51155091cfa816b8f085cf0cefa085af4250ff2390b9ecf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
