# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Grumble.destroy_all


Grumble.create(author: "Mr. Met", content: "Lets Go Mets! Hope they win today", title: "Chearing at the Mets Game", image: 'http://3.bp.blogspot.com/_-GckXqvg4yg/SkBfm2UN8ZI/AAAAAAAAAJs/MbfMVHQUqog/s400/mr-met3.jpg', avatar: 'http://newyork.mets.mlb.com/nym/images/fan_forum/mr_met_cartoon_126x200.jpg')
Grumble.create(author: "Philly Phanatic", content: "Lets Go Phillies!", title: "Phillies Game", image: 'http://www.rksportspromotions.com/sites/default/files/PhillyPhanaticPix.jpg', avatar: 'http://www.corbisimages.com/images/Corbis-42-34830694.jpg?size=67&uid=317fa414-91a0-4df6-86b3-ce047289a1ae')
Grumble.create(author: "Rocky Balboa", content: "YO ADRIAN, I DID IT!!!", title: "Heavyweight Champion of the World", image: 'http://stallonezone.com/imgs/news/2011/feb/021310rocky_belt.png', avatar: 'http://www.quotesworthrepeating.com/wp-content/uploads/2012/08/Rocky-Balboa.jpg')
Grumble.create(author: "Neo", content: "If you can dodge a bullet, you can dodge a ball!", title: "Dodgebullet", image: 'http://static.comicvine.com/uploads/scale_super/8/85165/1814286-neo.jpg', avatar: 'http://www.mobiletoones.com/downloads/wallpapers/movie_wallpapers/preview/27/37754-neo-matrix.jpg')
Grumble.create(author: "David Wright", content: "Time to hit the homerun. Lets Go Mets!", title: "Homerun Time", image: 'http://3.bp.blogspot.com/_-fg-4q7T3sg/TIQ3qx0N8GI/AAAAAAAADQg/4AMoKvU8THg/s1600/tumblr_l5btb7iCSV1qcd9b4o1_500.jpg', avatar: 'http://metsmerizedonline.com/wp-content/uploads/2009/08/David-Wright-256x300.jpg')
Grumble.create(author: "Mike Piazza", content: "New York Mets for Life!", title: "Catching the first pitch today", image: 'http://goldmedalimpressions.com/images/magictoolbox_cache/dd6b6cfc02e1715d9cb0915c3f4a72c2/1/8/18259/thumb400x600/5bee2f863aff6b9871bf528925882a40.jpg', avatar: 'http://www.nndb.com/people/454/000023385/mikepiazza01.jpg')
Grumble.create(author: "Michael Jordan", content: "Flashback to the Bulls Days. The days I established myself as the G.O.A.T.", title: "G.O.A.T.", image: 'http://readjack.files.wordpress.com/2010/06/jordan-last-shot.jpg', avatar: 'http://www.lovestars.info/Admin/uploaded_files/1289213782-michael-jordan-2.jpg')
Grumble.create(author: "LeBron James", content: "Chasing Jordan ain't easy but I'm up for it.", title: "LJ vs. MJ", image: 'http://blogsohardsports.com/wp-content/uploads/2013/04/jordan-says-lebron-not-successful-90s.jpg', avatar: 'http://susers.thatsmyface.com/r/ryanhudy/Lebron_James_left_LlxlAuBLn6.facecrop_204d9dfa.jpg')
Grumble.create(author: "Jerry Seinfeld", content: "What's the deal with airline food? Why does it taste so bad?", title: "Airline Food", image: 'http://www.quickmeme.com/img/7e/7eb92ff31d544387e38e7ba5a86482d2542d0ae66d8ec6d5b903dadddcdb442e.jpg', avatar: 'http://ia.media-imdb.com/images/M/MV5BMTI3MTU3MjgwM15BMl5BanBnXkFtZTcwMzIwNTM5MQ@@._V1_SX214_CR0,0,214,317_AL_.jpg')
Grumble.create(author: "Rick James", content: "Charlie Murphy comes in to my club... Time to show him some unity...", title: "Unity", image: 'http://cdn.buzznet.com/assets/users12/kingtola/default/rick-james-charlie-murphy--large-msg-115698337854.jpg', avatar: 'http://www.ireport.cz/images/ireport/clanky/Rick_James/rick_james_01.jpg')
Grumble.create(author: "Mr. Met", content: "Lets Go Mets! Hope they win today", title: "Chearing at the Mets Game", image: 'http://3.bp.blogspot.com/_-GckXqvg4yg/SkBfm2UN8ZI/AAAAAAAAAJs/MbfMVHQUqog/s400/mr-met3.jpg', avatar: 'http://newyork.mets.mlb.com/nym/images/fan_forum/mr_met_cartoon_126x200.jpg')
Grumble.create(author: "Mr. Met", content: "Lets Go Mets! Hope they win today", title: "Chearing at the Mets Game", image: 'http://3.bp.blogspot.com/_-GckXqvg4yg/SkBfm2UN8ZI/AAAAAAAAAJs/MbfMVHQUqog/s400/mr-met3.jpg', avatar: 'http://newyork.mets.mlb.com/nym/images/fan_forum/mr_met_cartoon_126x200.jpg')
Grumble.create(author: "Mr. Met", content: "Lets Go Mets! Hope they win today", title: "Chearing at the Mets Game", image: 'http://3.bp.blogspot.com/_-GckXqvg4yg/SkBfm2UN8ZI/AAAAAAAAAJs/MbfMVHQUqog/s400/mr-met3.jpg', avatar: 'http://newyork.mets.mlb.com/nym/images/fan_forum/mr_met_cartoon_126x200.jpg')
Grumble.create(author: "Mr. Met", content: "Lets Go Mets! Hope they win today", title: "Chearing at the Mets Game", image: 'http://3.bp.blogspot.com/_-GckXqvg4yg/SkBfm2UN8ZI/AAAAAAAAAJs/MbfMVHQUqog/s400/mr-met3.jpg', avatar: 'http://newyork.mets.mlb.com/nym/images/fan_forum/mr_met_cartoon_126x200.jpg')
Grumble.create(author: "Mr. Met", content: "Lets Go Mets! Hope they win today", title: "Chearing at the Mets Game", image: 'http://3.bp.blogspot.com/_-GckXqvg4yg/SkBfm2UN8ZI/AAAAAAAAAJs/MbfMVHQUqog/s400/mr-met3.jpg', avatar: 'http://newyork.mets.mlb.com/nym/images/fan_forum/mr_met_cartoon_126x200.jpg')
Grumble.create(author: "Mr. Met", content: "Lets Go Mets! Hope they win today", title: "Chearing at the Mets Game", image: 'http://3.bp.blogspot.com/_-GckXqvg4yg/SkBfm2UN8ZI/AAAAAAAAAJs/MbfMVHQUqog/s400/mr-met3.jpg', avatar: 'http://newyork.mets.mlb.com/nym/images/fan_forum/mr_met_cartoon_126x200.jpg')
Grumble.create(author: "Mr. Met", content: "Lets Go Mets! Hope they win today", title: "Chearing at the Mets Game", image: 'http://3.bp.blogspot.com/_-GckXqvg4yg/SkBfm2UN8ZI/AAAAAAAAAJs/MbfMVHQUqog/s400/mr-met3.jpg', avatar: 'http://newyork.mets.mlb.com/nym/images/fan_forum/mr_met_cartoon_126x200.jpg')
Grumble.create(author: "Mr. Met", content: "Lets Go Mets! Hope they win today", title: "Chearing at the Mets Game", image: 'http://3.bp.blogspot.com/_-GckXqvg4yg/SkBfm2UN8ZI/AAAAAAAAAJs/MbfMVHQUqog/s400/mr-met3.jpg', avatar: 'http://newyork.mets.mlb.com/nym/images/fan_forum/mr_met_cartoon_126x200.jpg')
Grumble.create(author: "Mr. Met", content: "Lets Go Mets! Hope they win today", title: "Chearing at the Mets Game", image: 'http://3.bp.blogspot.com/_-GckXqvg4yg/SkBfm2UN8ZI/AAAAAAAAAJs/MbfMVHQUqog/s400/mr-met3.jpg', avatar: 'http://newyork.mets.mlb.com/nym/images/fan_forum/mr_met_cartoon_126x200.jpg')
Grumble.create(author: "Mr. Met", content: "Lets Go Mets! Hope they win today", title: "Chearing at the Mets Game", image: 'http://3.bp.blogspot.com/_-GckXqvg4yg/SkBfm2UN8ZI/AAAAAAAAAJs/MbfMVHQUqog/s400/mr-met3.jpg', avatar: 'http://newyork.mets.mlb.com/nym/images/fan_forum/mr_met_cartoon_126x200.jpg')
