# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd9190628485e8ab776e93494f403e4a8bb74f6133737b2e644810ccce63f7d78b08f3abd84fc79f6b60e91681646fa69f04389f00e4438b60083930e2823ff3

test:
  secret_key_base: 114f2639d8c920de1cacae526d9cba0b444e9832be5ad6af6c27b0958270202a900d8329881c07d6735f0aaac213cd3add0893661e1ae03a6fabfc22bc473ec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
