# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61a063f5bb7090bcae0a0fedf20ffed33a3bd42936695f121c602ba93537d376fbfb11b00a65e542e5fa85e54a8062caee03aa74c25973057be228628f21484e

test:
  secret_key_base: e5f979187ca077dd65c74a2617ead967e98233255f9af56d131fd90e14b86d29c4312df9db153317dc2ccdc25727123ac7fd65e58d888f030401711376865ebe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
