DROP TABLE IF EXISTS buildings CASCADE;
DROP TABLE IF EXISTS apartments CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;
DROP TABLE IF EXISTS doormen CASCADE; 

CREATE TABLE buildings(
id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
address VARCHAR(510),
num_floors INTEGER
);

CREATE TABLE apartments( 
id SERIAL PRIMARY KEY, 
floor INTEGER, 
name VARCHAR(255) NOT NULL, 
price INTEGER, 
sqft INTEGER, 
bedrooms INTEGER,
bathrooms INTEGER,
building_id INTEGER REFERENCES buildings(id) 
);

CREATE TABLE tenants(
id SERIAL PRIMARY KEY, 
name VARCHAR(255) NOT NULL, 
age INTEGER, 
gender VARCHAR(255),
apartment_id INTEGER REFERENCES apartments(id)
);

CREATE TABLE doormen(
id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL, 
experience INTEGER, 
shift VARCHAR(255),
building_id INTEGER REFERENCES buildings(id) 
);