# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e7a997462530f86bdad23bead04c339f8eeb06c2bae0c9ffe80330f2e565429dc6d80c757ff007690d3996ec570e8dbd017be6dd26dff5e337a2d4a5e3d98da

test:
  secret_key_base: 1363dc4700b88c556b30338451a74b1a7abcae02d8c32ea4591c8f2d7931432f3870ab5c9db48b129e82d2917784674746bd79da1df8b86e67494de357c53a6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
