# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44ce55672dd8f75fa91d5e47931a21b8d86fc1f3726b800c5aa3b45480bc5c430e11b97cdd9747031ff6907001d895a5cfcb9327bb36ef46bab7f57b472d5a0f

test:
  secret_key_base: dae389aa69c89234176b9a6bf69bc052a42ab9b0aea3d74be485de557ed0f7b67fa272529b2eeab3ac0b785c662e75ed2df731469e414e302e2e7cee06a6d275

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
