# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1934cc4816af1e25847de30f19654cbd7da9a2a31617aba3e98d171c9a0a32c4960e4c4c9ad6761d9a7f7fbedc599727f79253885e4864e2ba6028d0b62e0f2e

test:
  secret_key_base: 104bb5befdb3c2ecd2b21df699281459ece3437da4f209745bf345eb7cc0588f4241a17019a68d3b5978e98e30581fc08b0f72d9cbd9a27e3b84bfd409188399

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
