TRUNCATE instructors;
TRUNCATE students;
TRUNCATE lessons;

INSERT INTO instructors (name, age) VALUES ('Hari', 50);
INSERT INTO instructors (name, age) VALUES ('Adam', 700);
INSERT INTO instructors (name, age) VALUES ('McK', 9001);

INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Albert', 'black', 12);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Alexander', 'blue', 25);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Alexandra', 'orange', 66);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Charlye', 'red', 43);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Christiana', 'green', 72);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Elizabeth', 'purple', 24);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Eric', 'blue', 23);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Francis', 'orange', 53);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Fen', 'blue', 62);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Gadi', 'red', 64);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Hoa', 'green', 76);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Jae', 'purple', 11);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('James', 'yellow', 12);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Jon', 'black', 63);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Khadijah', 'red', 36);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Liza', 'orange', 11);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Michael', 'green', 83);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Najee', 'purple', 99);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Patrick', 'yellow', 10);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Peter', 'white', 15);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Ranjan', 'teal', 32);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('Sarit', 'cyan', 16);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('SeanJ', 'sage', 61);
INSERT INTO students (name, favorite_color, favorite_number) VALUES ('SeanT', 'maroon', 79);

INSERT INTO lessons (week, day, topic) VALUES (1, 1, 'Classroom Culture');
INSERT INTO lessons (week, day, topic) VALUES (1, 1, 'Intro to Programming');
INSERT INTO lessons (week, day, topic) VALUES (1, 2, 'Computer Effectiveness');
INSERT INTO lessons (week, day, topic) VALUES (1, 2, 'Problem Modeling');
INSERT INTO lessons (week, day, topic) VALUES (1, 2, 'Collections and Enumeration');
INSERT INTO lessons (week, day, topic) VALUES (1, 3, 'Data Modeling');
INSERT INTO lessons (week, day, topic) VALUES (1, 3, 'Conditionals');
INSERT INTO lessons (week, day, topic) VALUES (1, 3, 'Methods');
INSERT INTO lessons (week, day, topic) VALUES (1, 4, 'More Methods');
INSERT INTO lessons (week, day, topic) VALUES (1, 4, 'Object-Oriented Programming');
INSERT INTO lessons (week, day, topic) VALUES (1, 5, 'Git and GitHub');
INSERT INTO lessons (week, day, topic) VALUES (2, 1, 'More OOP');
INSERT INTO lessons (week, day, topic) VALUES (2, 2, 'Inheritance');
INSERT INTO lessons (week, day, topic) VALUES (2, 3, 'Domains, Databases, SQL');
INSERT INTO lessons (week, day, topic) VALUES (2, 4, 'Relationships');
INSERT INTO lessons (week, day, topic) VALUES (2, 5, 'Surprise');
