# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64219cd6aa504039eae090d70924a76a7f2595e5091ff368177cb3407051e72caa109f0d238e9922767b333148a25a3e010af8374a5736c7eb537192101867ca

test:
  secret_key_base: 899eeee93570ae0fa959db4869774eb0b76819f99afeaf78c1cf17b2563e35b919dbeb357289f6376d835cd145c0f6fedc0eaff4ac0b7a4542c8dcd6327ba377

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
