# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 792417f6440cc194c7bfc67c4bbde1ac34cf16492445bda78abcb9b5b421483af554b5265a549f24eb4eb2491c2c4f944a9fa359622e2fcb515845df132d0179

test:
  secret_key_base: 84761cc8a1272c3595813860b1ebe1d917d7e16574b59373f23afb47f909963631647c66bf64317ab8bc8698ceac2376ac8328e7c5079e8ba45eb04299da7ea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
