# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69303e59ab08a9dcb4d7be26eccd7e133df7fa8d7fa520f92d6957d1b4f13abe5ad56db675fb88aff90b92ddd25a6c973049fe15bd6f620f5a845494c17e4185

test:
  secret_key_base: b11d0e70d85d5a989f07656ded88eea88af242222a8c97eb583a0c70acc35fe7fbf01d5cbc0b3a12ffc23366fd99b0bf1307a5b66246c0adcac0908ec34590ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
