# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fb1cfdd3fdeaf4e1a1227ff0474543ee7dfaad6d62c5e2a8c8d735b8cc3f51c3893ef60d44d51203746dad95c927eb840f8fe72e2a02353b3f8aeda1de17a79

test:
  secret_key_base: 6b316ea120222143761b083f4a4069b75560d8b8ce1a7e4735cb9f0198c0273bf51cecb70e7df5383adcfcc4569a1fc0d8c4e717c9299c2164f50d8472b54d0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
