# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff1720fe474adf51b8a7d189c9e6ee9db96e7f2297f2484cd92b5e2e76e03c6bd13aa4bbf1cd528d8fa68adddc59f65fc7d5b5fabee91a0db5a1c8b15014ef12

test:
  secret_key_base: c14b59baf95777b052f3652c32bf65a07bbf5ac4548bd59d620a2f9a94f4d3546e8a5d1faeb20e075fd0816347cb138efa32b3ffa39c3bd1ef85bb9461afd270

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
