# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b451b9e399ec5ecce00429cf90bc990b60badd2ec37deca49b91a2c37b2f9ad5a8f7ccacee1c57566875201e91a2421ac32425f7b660dab59041da2f73e1267

test:
  secret_key_base: 1825203e3f7e1d19f96a278efad36f162a4f5e9fec587f130a593776971f5e57048c4034ec2b87ed0c1842f14d6326fa69db232a9317714662234759303be5e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
