1. var grumble1 = new GrumbleModel({})
2. grumble1.set({author: 'Dr. Evil', title: 'Throw me a frickin\' bone here', content: 'My childhood was typical...summers in Rangoon; meat helmets in Spring.', image: 'http://cupofzup.com/wp-content/uploads/2014/07/giphy.gif', avatar: 'http://www.monarchwebsites.com/wp-content/uploads/dr-evil.jpg'})
3. grumble1.save()
4. grumble1.destroy()
5. var grumble2 = new GrumbleModel({author: 'Dr. Evil', title: 'Throw me a frickin\' bone here', content: 'My childhood was typical...summers in Rangoon; meat helmets in Spring.', image: 'http://cupofzup.com/wp-content/uploads/2014/07/giphy.gif', avatar: 'http://www.monarchwebsites.com/wp-content/uploads/dr-evil.jpg'})
6. grumble2.set('title', 'How can you be so obtuse?')
   grumble2.set('content', 'What? What did you call me? Son, you\'re forgetting yourself.')
7. var allGrumbles = new GrumblesCollection()
8. allGrumbles.fetch()
9. var myFavGrumble = allGrumbles.get({id: 22})
10. allGrumbles.remove(myFavGrumble)
11. allGrumbles.add({title: 'Oh you maaaaadddddd, you maaaddd!!!!', author: 'Cam\'ron', content: 'Damn he mad.', image: 'http://s3.amazonaws.com/rapgenius/you_mad_camron.jpg', avatar: 'http://i1.ytimg.com/vi/o8rCLfmhZEA/hqdefault.jpg'})
12. Backbone.sync("update", allGrumbles)

var grumble1 = new GrumbleModel({})
grumble1.set({author: 'Dr. Evil', title: 'Throw me a frickin\' bone here', content: 'My childhood was typical...summers in Rangoon; meat helmets in Spring.', image: 'http://cupofzup.com/wp-content/uploads/2014/07/giphy.gif', avatar: 'http://www.monarchwebsites.com/wp-content/uploads/dr-evil.jpg'})
grumble1.save()
grumble1.destroy()
var grumble2 = new GrumbleModel({author: 'Dr. Evil', title: 'Throw me a frickin\' bone here', content: 'My childhood was typical...summers in Rangoon; meat helmets in Spring.', image: 'http://cupofzup.com/wp-content/uploads/2014/07/giphy.gif', avatar: 'http://www.monarchwebsites.com/wp-content/uploads/dr-evil.jpg'})
grumble2.set('title', 'How can you be so obtuse?')
grumble2.set('content', 'What? What did you call me? Son, you\'re forgetting yourself.')
var allGrumbles = new GrumblesCollection()
allGrumbles.fetch()
var myFavGrumble = allGrumbles.get({id: 22})
allGrumbles.remove(myFavGrumble)
allGrumbles.add({title: 'Oh you maaaaadddddd, you maaaddd!!!!', author: 'Cam\'ron', content: 'Damn he mad.', image: 'http://s3.amazonaws.com/rapgenius/you_mad_camron.jpg', avatar: 'http://i1.ytimg.com/vi/o8rCLfmhZEA/hqdefault.jpg'})
Backbone.sync("update", allGrumbles)
