# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cae02c183e09cc0266011d5682298ad946814abfdfaeb64a204464ea76aef185898d3d0d25a72e96b667408c932f4531c40dc254088ff82af0fe1fac983cb80a

test:
  secret_key_base: fde3dabdafe3044dcaa9019fdd93f5f536912a26025ea2ddbdbe51d6eb446e01346e0bb14c2fe6498eb7f88191e6cfa7a12bcda149459f4ccf0d2255586091b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
